set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "MacJMP for macOS")
set(CPACK_PACKAGE_VENDOR "MacJMP")
set(CPACK_PACKAGE_NAME "MacJMP")
set(CPACK_PACKAGE_VERSION_MAJOR ${VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${VERSION_NANO})

set(CPACK_SYSTEM_NAME "macos-arm64")
set(CPACK_PACKAGE_FILE_NAME "macjmp-${VERSION_STRING}-${CPACK_SYSTEM_NAME}")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "macjmp-${VERSION_STRING}-src")

set(CPACK_PACKAGE_INSTALL_DIRECTORY "MacJMP")
set(CPACK_STRIP_FILES 1)

set(CPACK_GENERATOR "ZIP")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY 0)
configure_file(${CMAKE_SOURCE_DIR}/CMakeModules/CPackGeneratedConfig.cmake.in ${CMAKE_BINARY_DIR}/CPackGeneratedConfig.cmake)
set(CPACK_PROJECT_CONFIG_FILE ${CMAKE_BINARY_DIR}/CPackGeneratedConfig.cmake)

include(CPack)
cpack_add_component(Core DISPLAY_NAME "MacJMP" DESCRIPTION "MacJMP macOS application" REQUIRED)
